[env:esp32cam-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB

build_flags =
  -DBOARD_HAS_PSRAM
  -DCAMERA_MODEL_FREENOVE_ESP32_S3_WROOM

lib_deps =
  espressif/esp32-camera @ ^2.0.4
