[platformio]
default_envs = nano33iot

[env:nano33iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>
lib_deps =
  arduino-libraries/ArduinoBLE @ ^2.0.0
  arduino-libraries/WiFiNINA @ ^2.0.0
