[platformio]
default_envs = nano33iot-ota

[env:nano33iot-ota]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<ota/ota_main.cpp>
lib_deps =
  jandrassy/ArduinoOTA @ ^1.1.1
  arduino-libraries/WiFiNINA @ ^1.8.14

[env:nano33iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>
lib_deps =
  arduino-libraries/ArduinoBLE @ ^2.0.0
  jandrassy/ArduinoOTA @ ^1.1.1
  arduino-libraries/WiFiNINA @ ^2.0.0
